from fpdf import FPDF
import os
from datetime import datetime

class BlueprintPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.cell(0, 10, "Your Soul Blueprint", ln=True, align="C")
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.cell(0, 10, f"Generated by SoulAligned.Life – {datetime.utcnow().year}", align="C")

    def add_section(self, title, content):
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(40, 40, 40)
        self.cell(0, 10, title, ln=True)

        self.set_font("Helvetica", "", 11)
        self.set_text_color(60, 60, 60)
        self.multi_cell(0, 8, content)
        self.ln(4)

def generate_pdf(user_name: str, email: str, blueprint_keys: dict, output_path: str = "soul_blueprint.pdf"):
    output_folder = "outputs"
    os.makedirs(output_folder, exist_ok=True)
    full_path = os.path.join(output_folder, output_path)

    pdf = BlueprintPDF()

    # Cover page
    pdf.add_page()
    pdf.image("cover.pdf", x=0, y=0, w=210, h=297)

    # Content page
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.image("background.pdf", x=0, y=0, w=210, h=297)

    # Intro
    pdf.set_font("Helvetica", "", 12)
    pdf.set_text_color(20, 20, 20)
    pdf.multi_cell(0, 10, f"Dear {user_name},

This report is a reflection of your unique energetic design — a map of your emotional, mental, and soul-aligned blueprint.")
    pdf.ln(8)

    # Add each Soul Step section
    for key, value in blueprint_keys.items():
        if key not in ['Life Path Number', 'Destiny Number']:
            pdf.add_section(key, value)

    # Add numerology info
    pdf.add_section("Numerology Insight", f"Life Path Number: {blueprint_keys.get('Life Path Number')}
Destiny Number: {blueprint_keys.get('Destiny Number')}")

    pdf.output(full_path)
    return full_path
